### ISSUE TITLE
[TranslateZed] Suggestion: add original text in Translate tab

### ISSUE THREAD

**Issue by richardfat7** [TheIndieStone/ProjectZomboidTranslations#166]
In TranslateZed tool, in translate tabs, I can see the key value row, but as a not so full experienced player of PZ, I found it a little hard to translate if I only look at the key. The tool will show the original text for newly added key, but if value of old key changed (in case adding something to description etc), it is very hard to notice that if I only look at the translated text. It will also be better for late coming to evaluate if the translation is good enough or not if they can see the original text.
My idea is to show 3 field, key value and value for EN, so we can have side to side comparison.

**Comment by richardfat7** [comment]
I realize I can see the english text when I hover on the value, but I still think it is better to show it side by side, which is easier for translator to read

**Comment by Connall** [comment]
Done.
