### ISSUE TITLE
IGUI_HotbarAttachment NOT WORK

### ISSUE THREAD

**Issue by Mishasama** [TheIndieStone/ProjectZomboidTranslations#173]
Check these pic.
![~IO491(YW668I(}$O5_21UO](https://user-images.githubusercontent.com/54498172/72062995-3afd4880-331c-11ea-8a59-7c3466c3e8d8.png)
![`4{ I 82KT0Q4~AQWBHS8MY](https://user-images.githubusercontent.com/54498172/72062997-3b95df00-331c-11ea-949a-6bf5bdf7901a.png)

**Comment by Connall** [comment]
This is due to the nature of how the feature was implemented. I can't do anything about this for now.


Closing.
