### ISSUE TITLE
Removing the commas

### ISSUE THREAD

**Issue by Zonary** [TheIndieStone/ProjectZomboidTranslations#176]
Every time you save, the tool removes the commas. Example: I changed the line, adding the comma, hit save. Checked in the game, the comma is there. Exited the game and opened the tool again to change another line, saved. When I opened the game again, the comma was gone

**Comment by Mishasama** [comment]
And it will delete all lines without a key.

**Comment by Connall** [comment]
I can't replicate the loss of commas, there was a similar bug but was fixed in an earlier version.
