### ISSUE TITLE
Improve Chinese Translations

### ISSUE THREAD

**Issue by joedai** [TheIndieStone/ProjectZomboidTranslations#181]
There are quite a few things that are still in English that are not translated into Chinese properly.

![image](https://user-images.githubusercontent.com/6591471/73601809-ed979280-45cc-11ea-8fae-2158c9c6ca83.png)

I've played the game for over 200 hours and I'd like to make my contribution. @Connall if you could allow me to join as a contributor.

Cheers,
Joe

**Comment by Connall** [comment]
There are two Chinese versions. Are you talking about the one in the CN folder or the one in the CH folder?

**Comment by joedai** [comment]
> There are two Chinese versions. Are you talking about the one in the CN folder or the one in the CH folder?

I was talking about the CN folder, but I am happy to help with the CH version as well, they are more of the same. I am a native CN speaker BTW.

**Comment by Mishasama** [comment]
CN project is here, please join us.
https://github.com/Mishasama/ProjectZomboidTranslations

**Comment by Mishasama** [comment]
@Connall Is there possible to provide the ItemName_EN.txt file? We need to find it ourselves now, it's super hard work if we haven't a guy know how to get the new keys without it.
And we can't track the DisplayName changes without it if we don't use the Items_XX.txt file.
