### ISSUE TITLE
NEED ItemName_EN.txt

### ISSUE THREAD

**Issue by Mishasama** [TheIndieStone/ProjectZomboidTranslations#182]
Is there possible to provide the full and keep updated ItemName_EN.txt file?
We need to find the new keys ourselves now, it's super hard work if we haven't a guy know how to get the new keys without it.
And we can't track the DisplayName changes without it if we don't use the Items_XX.txt file.

**Comment by Connall** [comment]
The translation tool allows you to generate the file yourself, however I shall update the file now.
