### ISSUE TITLE
UI_XX "About Mods" can't display double byte character

### ISSUE THREAD

**Issue by Mishasama** [TheIndieStone/ProjectZomboidTranslations#197]
EN\UI_EN.txt

Line 550 under the EN file:
UI_ModsNagPanel_Title = "About Mods"

It can't display character like Japanese or Chinese.
![image](https://user-images.githubusercontent.com/54498172/78220846-3ef4cd00-74fd-11ea-8dda-c662cd290e8c.png)

**Comment by Mishasama** [comment]
It should be a font problem.

**Comment by nsKpz** [comment]
This can be fixed by changing which font is used in media/fonts/CN/fonts.txt, for the Cred2 font. The non-English languages are using zombiefontcredits2.fnt.
