### ISSUE TITLE
Add starting town descriptions to EN

### ISSUE THREAD

**Issue by Faalagorn** [TheIndieStone/ProjectZomboidTranslations#288]
English files are missing folders with descriptions of the starting cities (`Muldraugh, KY`, `Riverside, KY`, `Rosewood, KY`, `West Point, KY` with `description.txt` and `title.txt` files inside.

I don't know where exactly they are taken from in the English game and the new `title.txt` files are mostly empty anyway, but I think it would be nice to have the original files uploaded here as well, even if just for reference for translators not using the TranslationZed.

**Comment by nsKpz** [comment]
Thanks, added onto our internal list.
