### ISSUE TITLE
Add debug menus strings for translations

### ISSUE THREAD

**Issue by Faalagorn** [TheIndieStone/ProjectZomboidTranslations#301]
Currently the strings available in the debug menu that's available when you launch game with `-debug` (or holding shift) cannot be translated resulting in a mix of English and translated strings.
![108600_20200627221811_1](https://user-images.githubusercontent.com/4951331/85931391-82749280-b8c4-11ea-8e3a-6e8ea853dbff.png)

**Comment by nsKpz** [comment]
This is already on the list.
