### ISSUE TITLE
"KpH" string can not be translated

### ISSUE THREAD

**Issue by Faalagorn** [TheIndieStone/ProjectZomboidTranslations#309]
The "KpH" and probably other strings that reflect units that are being broadcasted in Automated Emergency Broadcast can not be translated and seems to be hardcoded in the game.

P.S. The "KpH" is not a correct unit either, it should either be *km/h* or *kph*, big K is for Kelvin and big H seems to be for Henry

**Comment by nsKpz** [comment]
Am I misunderstanding or would this not be part of making radio broadcasts translatable?

**Comment by Faalagorn** [comment]
It should, but it seems it's hidden behind a `%s` string: https://github.com/TheIndieStone/ProjectZomboidTranslations/blob/master/EN/DynamicRadio_EN.txt#L12

**Comment by nsKpz** [comment]
Ah. Yeah that'll cover it but I'll make sure to add this to our list specifically, regardless :)
