### ISSUE TITLE
Something can't be translate.

### ISSUE THREAD

**Issue by Mishasama** [TheIndieStone/ProjectZomboidTranslations#322]
# Broken Glass
![image](https://user-images.githubusercontent.com/54498172/89107665-997f4500-d46d-11ea-9793-a81498e7b6d7.png)
![image](https://user-images.githubusercontent.com/54498172/89107684-bca9f480-d46d-11ea-9307-91cd92afb0ee.png)
# Audio - Advanced
![image](https://user-images.githubusercontent.com/54498172/90241272-aafd1f80-de65-11ea-9ba1-cd84f69f57ba.png)

I can't found the string in files.

**Comment by nsKpz** [comment]
For Broken Glass you can add

`    Broken_Glass = "YOUR TRANSLATION HERE",
`
to the Movables_XX.txt.

For the Advanced Audio tab, you will translate the GameSounds_EN.txt to your language. The categories can be translated via adding GameSound_Category_XXXXX = "XXXXX" to the GameSounds_XX.txt

**Comment by Faalagorn** [comment]
Maybe they could be added to respective English files then? We could make translation to the sound names while at it; should I start working on it in the spare time?

**Comment by nsKpz** [comment]
Yeah, they should be added. I've already done part of it so will probably be ready for .42 or .43
