### ISSUE TITLE
ContextMenu_Put_in_Container not working.

### ISSUE THREAD

**Issue by Mishasama** [TheIndieStone/ProjectZomboidTranslations#329]
![image](https://user-images.githubusercontent.com/54498172/90316655-83d64900-df5e-11ea-823a-4e451b5450c5.png)

**Comment by ditoseadio** [comment]
Obsolete.
New one is:

ContextMenu_PutInContainer = "Put in Container (%1)",

**Comment by Faalagorn** [comment]
Is it still relevant @Mishasama? If not, guess it can be closed?

**Comment by Mishasama** [comment]
Obsolete.
But maybe we should delete this line because it is no longer work? @Faalagorn

**Comment by Faalagorn** [comment]
@nsKpz Can you confirm the string is no longer used? If so, I'll make PR removing it from EN, though I see other languages have it translated.
