### ISSUE TITLE
Missing lines in recipes and itemname

### ISSUE THREAD

**Issue by Mishasama** [TheIndieStone/ProjectZomboidTranslations#331]
![1](https://user-images.githubusercontent.com/54498172/90765434-da5bd280-e324-11ea-84dc-8c617c5f8784.png)
Mug of Water + Tea Bag

And many more...

These things can't be translated before we know the keys.

**Comment by nsKpz** [comment]
This is 
ContextMenu_EvolvedRecipe_HotDrink = "Beverage", 

in the ContextMenu_XX.txt

**Comment by Mishasama** [comment]
> This is
> ContextMenu_EvolvedRecipe_HotDrink = "Beverage",
> 
> in the ContextMenu_XX.txt

![image](https://user-images.githubusercontent.com/54498172/91206173-af68e880-e741-11ea-9026-4d79c4744aa2.png)
No, it doesn't work.
The "Tea" can't be translated.
And the "Prepare Beverage" not found too.
