### ISSUE TITLE
Moveables typos & and missing ones

### ISSUE THREAD

**Issue by ditoseadio** [TheIndieStone/ProjectZomboidTranslations#366]
Typo on:

Mounted_Deer_Thropy = "Mounted Deer Thropy",

**Comment by ditoseadio** [comment]
![image](https://user-images.githubusercontent.com/39344013/95232524-876aab80-07fc-11eb-9571-417aedc4a54b.png)

**Comment by ditoseadio** [comment]
GameSound missing strings

GameSound_BreakBarricadePlank = "",
GameSound_BreakBarricadeMetal = "",
GameSound_ZombieBite = "",


And typo on:
GameSound_CheckFighingNet (it should be GameSound_CheckFi**s**hingNet)

**Comment by Faalagorn** [comment]
I guess they can be added in a PR? If that's a preferred way, I think I can do so during the week and fix the typos in English, though ideally all languages should get the strings to translate, right?

**Comment by Faalagorn** [comment]
@ditoseadio Where do you take these names from? Is it TileZed or some other program? I'm thinking of doing the PR to add these names but I see the Mounted Deer Trophy is already there as it should, both in code and in game: https://github.com/TheIndieStone/ProjectZomboidTranslations/blob/master/EN/Moveables_EN.txt#L399
