### ISSUE TITLE
About missing translation lines

### ISSUE THREAD

**Issue by moonlight-pz** [TheIndieStone/ProjectZomboidTranslations#441]
@nsKpz 

The player told us that some translation lines were missing. we found some translation lines. It's not in English. Submit to you

41.50
Sandbox_CN.txt
    Sandbox_ZCrawlUnderVehicle = "爬过车底",
    Sandbox_ZCrawlUnderVehicle_option1 = "从不",
    Sandbox_ZCrawlUnderVehicle_option2 = "非常少",
    Sandbox_ZCrawlUnderVehicle_option3 = "稀少",
    Sandbox_ZCrawlUnderVehicle_option4 = "有时",
    Sandbox_ZCrawlUnderVehicle_option5 = "经常",
    Sandbox_ZCrawlUnderVehicle_option6 = "非常多",
    Sandbox_ZCrawlUnderVehicle_option7 = "全部",

Recipes_CN.txt
    Recipe_Advanced_Mechanics = "莱恩斯汽车手册-性能车型",
    Recipe_Basic_Mechanics = "莱恩斯汽车手册-标准车型",
    Recipe_Intermediate_Mechanics = "莱恩斯汽车手册-商用车型",

another

When there is a female corpse in the inventory, it will become the icon of a male corpse. Maybe this is a bug?

**Comment by Faalagorn** [comment]
Thanks for noticing it! Can you tell me when these recipes are being used? I can't find the place they are used in-game.

> Recipe_Advanced_Mechanics = "莱恩斯汽车手册-性能车型",
> Recipe_Basic_Mechanics = "莱恩斯汽车手册-标准车型",
> Recipe_Intermediate_Mechanics = "莱恩斯汽车手册-商用车型",

**Comment by moonlight-pz** [comment]
> Thanks for noticing it! Can you tell me when these recipes are being used? I can't find the place they are used in-game.
> 
> > Recipe_Advanced_Mechanics = "莱恩斯汽车手册-性能车型",
> > Recipe_Basic_Mechanics = "莱恩斯汽车手册-标准车型",
> > Recipe_Intermediate_Mechanics = "莱恩斯汽车手册-商用车型",

Sure! Please look at the picture, it is not easy to find, I marked it.
![T01](https://user-images.githubusercontent.com/70738769/105578123-f9b9c880-5db8-11eb-8105-36f72aa06374.png)
![T02](https://user-images.githubusercontent.com/70738769/105578129-01796d00-5db9-11eb-9b02-ded8f185ce75.png)
![T03](https://user-images.githubusercontent.com/70738769/105578135-063e2100-5db9-11eb-8c0c-bcd9431571a7.png)

The names of the three books are as follows.

 "Laines Auto Manual - Standard Models",
 "Laines Auto Manual - Commercial Models",
 "Laines Auto Manual - Performance Models"

**Comment by Faalagorn** [comment]
Thanks! I'll try to sent PR that adds them to EN version so they should appear in Translation Zed and be easier to translate for new languages – if you have the original English strings, that'd help, if not I'll figure them out :)

In the meantime, you should be able to fix it by adding these strings to your translation by adding the relevant strings manually, similar to what happened with #366. :)

**Comment by moonlight-pz** [comment]
> Thanks! I'll try to sent PR that adds them to EN version so they should appear in Translation Zed and be easier to translate for new languages – if you have the original English strings, that'd help, if not I'll figure them out :)
> 
> In the meantime, you should be able to fix it by adding these strings to your translation by adding the relevant strings manually, similar to what happened with #366. :)
--------------------------------------------------------------------------------------------------------------------------------------
Sorry, we do not have an EN version. The player only gave us the Chinese version.

The Chinese translation has added these. If we find the missing translation line again, we will record the EN version and CN version, and then submit it to you
