### ISSUE TITLE
Missing translations for Oak Right Bar, Oak Middle Bar and Oak Left Bar

### ISSUE THREAD

**Issue by Faalagorn** [TheIndieStone/ProjectZomboidTranslations#451]
It seems that the new furniture in Muld new shop are missing names though I didn't try adding them yet to Moveables files.
@ditoseadio or @moonlight-pz you guys might take a look :)

![screenshot_2021-02-08-204151](https://user-images.githubusercontent.com/4951331/107273217-0a23a180-6a4f-11eb-84cd-56d1fa3c6b72.png)
![screenshot_2021-02-08-204147](https://user-images.githubusercontent.com/4951331/107273218-0b54ce80-6a4f-11eb-891d-c34496a4c002.png)
![screenshot_2021-02-08-204143](https://user-images.githubusercontent.com/4951331/107273221-0bed6500-6a4f-11eb-84c0-bfad85189131.png)

**Comment by moonlight-pz** [comment]
If you remember the detailed address, can you provide it? I did not find the shop you mentioned.

**Comment by Faalagorn** [comment]
Yup, I reported that on forum as well: https://theindiestone.com/forums/index.php?/topic/33705-issues-with-oak-right-bar-oak-middle-bar-and-oak-left-bar/&tab=comments#comment-306485 :)

**Comment by moonlight-pz** [comment]
@Faalagorn 

Hi guys!More missing translation lines. It originated here.
https://github.com/moonlight-pz/ProjectZomboidTranslations/pull/20

Related books:
	ItemName_Base.MetalworkMag1 = "The Metalwork Magazine Vol. 1",
	ItemName_Base.MetalworkMag2 = "The Metalwork Magazine Vol. 2",
	ItemName_Base.MetalworkMag3 = "The Metalwork Magazine Vol. 3",

english
	Recipe_Make_Metal_Fences = "Make Metal Fences",
	Recipe_Make_Metal_Containers = "Make Metal Containers",
	Recipe_Make_Metal_Walls = "Make Metal Walls",
	Recipe_Make_Metal_Roof = "Make Metal Roof",
chinese
	Recipe_Make_Metal_Fences = "制作金属栅栏",
	Recipe_Make_Metal_Containers = "制作金属容器",
	Recipe_Make_Metal_Walls = "制作金属墙",
	Recipe_Make_Metal_Roof = "制作金属屋顶",
