### ISSUE TITLE
Missing translations for some moveables

### ISSUE THREAD

**Issue by Faalagorn** [TheIndieStone/ProjectZomboidTranslations#456]
The `!` is from debug option which shows untranslated signs, follow up to #451 @ditoseadio @moonlight-pz 

![screenshot_2021-02-21-124649](https://user-images.githubusercontent.com/4951331/108625710-9d47d880-744c-11eb-8c3c-bf82da9ba5ce.png)
![screenshot_2021-02-21-124605](https://user-images.githubusercontent.com/4951331/108625712-9e790580-744c-11eb-809d-d9478536efed.png)
![screenshot_2021-02-21-123202](https://user-images.githubusercontent.com/4951331/108625719-a8026d80-744c-11eb-9e7a-141256dad98b.png)
![screenshot_2021-02-20-004809](https://user-images.githubusercontent.com/4951331/108625728-ba7ca700-744c-11eb-9263-d3b98e227354.png)

**Comment by moonlight-pz** [comment]
Can the detailed locations of these items be marked on the map? Translation tests need to find these items.

**Comment by Faalagorn** [comment]
Sure, starting from the top:
https://map.projectzomboid.com/#5757x6489

https://map.projectzomboid.com/#5779x6462

https://map.projectzomboid.com/#14126x5492 (not the location from the screenshot, but the item should be the same)

The Big Spiffo might be somewhere on the map, but I found it in the tutorial, to access move menu I followed the guide [here](https://www.reddit.com/r/projectzomboid/comments/dw2a69/kingsmouth_in_sandbox/f7h6ba7/) and made a custom `spawnpoints.lua` to not spawn out of bounds and teleported with debug command (I used unemployed), I copied existing ones but you probably can remove other jobs or modify it accordingly to spawn anywhere else:

```
function SpawnPoints()
return {
  constructionworker = {
    { worldX = 1, worldY = 1, posX = 183, posY = 118, posZ = 0 }
  },
  fireofficer = {
    { worldX = 1, worldY = 1, posX = 183, posY = 118, posZ = 0 }
  },
  parkranger = {
    { worldX = 1, worldY = 1, posX = 183, posY = 118, posZ = 0 }
  },
  policeofficer = {
    { worldX = 1, worldY = 1, posX = 183, posY = 118, posZ = 0 }
  },
  securityguard = {
    { worldX = 1, worldY = 1, posX = 183, posY = 118, posZ = 0 }
  },
  unemployed = {
    { worldX = 0, worldY = 0, posX = 100, posY = 100, posZ = 0 }
  }
}
end
```

**Comment by moonlight-pz** [comment]
It is provided by @RunAbout996 .There is no problem with the Chinese translation test, you can try other languages.

English
Blue_Canopy = "Blue Canopy",
Large_Wide_Mirror = "Large Wide Mirror",
Pallet_With_Bricks = "Pallet With Bricks",
Big_Wall_Spiffo = "Big Wall Spiffo",

Simplified Chinese
Blue_Canopy = "蓝色遮挡棚",
Large_Wide_Mirror = "大型宽镜",
Pallet_With_Bricks = "砖块托盘",
Big_Wall_Spiffo = "斯皮福大壁纸",

**Comment by Faalagorn** [comment]
> It is provided by @RunAbout996 .Although we still didn’t find Big Wall Spiffo in the game, we searched the game file and found its group name and custom name. This translation line should be correct, hope you can help us test it.
> ![1](https://user-images.githubusercontent.com/70738769/108851354-4ba37780-761f-11eb-951f-b9680bd1246f.png)
Thanks! I'll take a look though I still have to sent a PR with English strings for #451 while @nsKpz is probably mad at the amount of PRs he have to go through already :P though the Big Wall Spiffo is like I said only found on Tutorial map – you can import it by following the guide I linked and using my `spawnpoints.lua` file if you want to test it yourself. :)

**Comment by moonlight-pz** [comment]
We found it, and it is correct in the Chinese translation. So this translation line is correct
![1](https://user-images.githubusercontent.com/70738769/108958504-0b3f0a80-76ae-11eb-8443-4a48bb2f690b.png)
