### ISSUE TITLE
Add TV and radio translations

### ISSUE THREAD

**Issue by Faalagorn** [TheIndieStone/ProjectZomboidTranslations#477]
As some people has been asking around, maybe it's best to add the translation files here? In the meantime, I've created a rough readme update with #476.

**Comment by Alnitak256** [comment]
I agree, I think that all translations should be in one place.

**Comment by Faalagorn** [comment]
I think the problem is that the files are in different format and they are waiting for the electricity revamp to unify it, but maybe in the meantime it might be possible for them to upload them as is on here @nsKpz? There were some VHS videos teased so that would need translations as well, maybe it's a right time to take care of it now :)

**Comment by Mishasama** [comment]
But... It is placed in a different folder. It can't just be put in this directory tree.

**Comment by Faalagorn** [comment]
> But... It is placed in a different folder. It can't just be put in this directory tree.

If you want to just symlink this folder as is and pull changes from github, then it could be troublesome (though nothing clever symlinking or even a simple ba{tch,sh} script couldn't solve.

Also, doesn't the TV translations currently require editing before they are usuable in the game in the first place? I'm not sure, as I didn't fiddle with them.

Either way, it's mostly about easily tracking changes and translations :). Ideally, translations could be done via external source such as Crowdin or Transifex though, but placing them on GitHub would still make translating them easier for some surely. :)

**Comment by Mishasama** [comment]
We can make a repository to do it before TIS did it for us ;)

**Comment by Faalagorn** [comment]
> We can make a repository to do it before TIS did it for us ;)

Yeah, though I'd love to have it in official one eventually :)
