### ISSUE TITLE
Tee-see wants to contribute!

### ISSUE THREAD

**Issue by Tee-see** [TheIndieStone/ProjectZomboidTranslations#50]
Hello there @Connall ,

Can you please add me as a contributor so I can update the French files?

Also, do I need to copy the whole Master repo or is it possible to work on the FR folder only and make a partial merge to master?

Thank you :)

**Comment by Connall** [comment]
Added you as a contributor but still says it's waiting on you to accept. In the meantime I have created a french branch for you, work on the french branch and do a pull request with master. It's locked to prevent people adding stuff to it without my go ahead.

**Comment by Tee-see** [comment]
Hey! Thanlks for the add, but oddly, I don't see a way to accept any kind of invite. I'll try to contribute to the FR branch and see how it turns out.

**Comment by Tee-see** [comment]
Okay, well, I cant' edit the FR branch because I don't have the required rights. Looks like my only way to edit so far is to fork. Are you sure I'm the one you added?

**Comment by Connall** [comment]
https://github.com/TheIndieStone/ProjectZomboidTranslations/invitations

**Comment by Tee-see** [comment]
All good now ! Thanks !
