### ISSUE TITLE
Bad state of Polish translation

### ISSUE THREAD

**Issue by Patrxgt** [TheIndieStone/ProjectZomboidTranslations#694]
Many of items are not translated or are half translated. Same goes to the tutorial, where half of it is in Polish and half is in English and even one line in the tutorial is half translated into Polish, then cut off and then started over in English.

**Comment by Faalagorn** [comment]
I guess it's no longer relevant @geras-PL? If so, I guess you can close it @nsKpz?

**Comment by geras-PL** [comment]
Ah, complaining about fan-made translation of an Early Access game being unfinished. Comedy gold.
Please close this.

**Comment by Patrxgt** [comment]
> Ah, complaining about fan-made translation of an Early Access game being unfinished. Comedy gold. Please close this.

Ah yes, salty translators, that can't even do their job, when other Early Access games have proper translations without salty excuses. Standard.

**Comment by nsKpz** [comment]
****
