### ISSUE TITLE
Need to re-transcode Recorded_Media_CH to Big5

### ISSUE THREAD

**Issue by eva08maicy02** [TheIndieStone/ProjectZomboidTranslations#729]
I'm sorry this happened, I have no clue as to why this happened. Now the encoding of Recorded_Media_CH is not correct, it needs to be re-converted to the correct Big5.

**Comment by mrazgrass** [comment]
fixed in #731

**Comment by mrazgrass** [comment]
@nsKpz Would you close this as solved? Thank you a bunch!
