### ISSUE TITLE
[Tradition Chinese]Moddles.txt string in game is unreadable.

### ISSUE THREAD

**Issue by dfr1238** [TheIndieStone/ProjectZomboidTranslations#847]
PZ Version : 41.73-41.77

OS : Windows 11 Pro - 22621.521

## OS Language, Region Setting
Taiwan, Tradition Chinese
Windows Un-Unicode Program Setting : Chinese (Taiwan, Tradition Chinese)

## Screenshot
![steamwebhelper_jHyGbGrQz5](https://user-images.githubusercontent.com/48888992/194764024-b7be768f-8f3e-4428-875a-031e1cc1d9f0.png)
![steamwebhelper_2qo6gyLjjd](https://user-images.githubusercontent.com/48888992/194764025-971ead8a-598b-4d89-84ab-6b698c5c382c.png)
![steamwebhelper_yO6DfiIeBE](https://user-images.githubusercontent.com/48888992/194764027-7ecb5996-126d-4b97-829c-340054eec3c7.png)

DxDiag:
[DxDiag.txt](https://github.com/TheIndieStone/ProjectZomboidTranslations/files/9741847/DxDiag.txt)

**Comment by mrazgrass** [comment]
![image](https://user-images.githubusercontent.com/17330709/197208269-d3549fdb-c124-40b5-ba6c-a4fa2dec8db1.png)
Doesn't seem to be a problem on my end. At least not anymore!

**Comment by iknowitseasier** [comment]
> ![image](https://user-images.githubusercontent.com/17330709/197208269-d3549fdb-c124-40b5-ba6c-a4fa2dec8db1.png) Doesn't seem to be a problem on my end. At least not anymore! Can you verify if the issue is still there on your machine after updating to 41.78 UNSTABLE?
> 
> PZ: 41.78 UNSTABLE OS: Windows 11 Home - English (United States)

I encountered the same issue and had to save Moodles_CH.txt with UTF-8 to fix the problem.

**Comment by mrazgrass** [comment]
> > ![image](https://user-images.githubusercontent.com/17330709/197208269-d3549fdb-c124-40b5-ba6c-a4fa2dec8db1.png) Doesn't seem to be a problem on my end. At least not anymore! Can you verify if the issue is still there on your machine after updating to 41.78 UNSTABLE?
> > PZ: 41.78 UNSTABLE OS: Windows 11 Home - English (United States)
> 
> I encountered the same issue and had to save Moodles_CH.txt with UTF-8 to fix the problem.

Please verify if the issue still occurs on 41.78 UNSTABLE version of the game. It should be fixed with that version.

**Comment by iknowitseasier** [comment]
> > > ![image](https://user-images.githubusercontent.com/17330709/197208269-d3549fdb-c124-40b5-ba6c-a4fa2dec8db1.png) Doesn't seem to be a problem on my end. At least not anymore! Can you verify if the issue is still there on your machine after updating to 41.78 UNSTABLE?
> > > PZ: 41.78 UNSTABLE OS: Windows 11 Home - English (United States)
> > 
> > 
> > I encountered the same issue and had to save Moodles_CH.txt with UTF-8 to fix the problem.
> 
> Please verify if the issue still occurs on **41.78 UNSTABLE** version of the game. It should be fixed with this version.
> 
> ![image](https://user-images.githubusercontent.com/17330709/198036478-7a9aabbd-2163-4971-9be7-9a9b6fb60220.png)

Just checked, it's fixed in 41.78. Thanks!

**Comment by mrazgrass** [comment]
Great! I'm glad the issue has been resolved 😄
